name: flutter_ad_format_helpers_example
description: Example project for our flutter_ad_format_helpers package.
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_ad_format_helpers:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  assets:
    - assets/demo-banner.jpg